# Generated by Django 4.2.26 on 2025-11-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_location_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
